### ISSUE TITLE
PHP 7.4 + Magento 2.4 compatibility.

### ISSUE THREAD

**Issue by PorraphitChuasuk** [magespecialist/m2-MSP_BackendGoogleSignOn#3]
Please consider to make this plugin compatible with Magento 2.4 and PHP 7.4

https://github.com/magespecialist/m2-MSP_BackendGoogleSignOn/blob/f0da3e8bc80a25aa8e6f81e1671a8edc613016d5/composer.json#L5

Thank you in advance.

**Comment by mikimpe** [comment]
The plugin is now compatible with Magento 2.4 and PHP 7.4
